reddit_clone/reddit_clone/config/routes.rb
Rails.application.routes.draw do

  resources :comments, except: [:index, :show]
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :links
end

reddit_clone/reddit_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

reddit_clone/reddit_clone/app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, :user_id, :title, :url, :sub_id, presence: true

  belongs_to :user
  belongs_to :sub
  
end

reddit_clone/reddit_clone/app/models/link.rb
class Link < ApplicationRecord
  validates :title, :url, :user_id, presence: true

  belongs_to :user
  has_many :comments
end

reddit_clone/reddit_clone/app/models/user.rb
class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}

  attr_reader :password
  after_initialize :ensure_session_token

  has_many :links
  has_many :comments

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    if user && user.is_password?(password)
      return user
    else
      nil
    end
  end

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end
end

reddit_clone/reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :logged_in?, :current_user

  def logged_in?
    !!current_user

  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end

end

reddit_clone/reddit_clone/app/controllers/comment_controller.rb
class CommentController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end
end

reddit_clone/reddit_clone/app/controllers/links_controller.rb
class LinksController < ApplicationController
  def new
    @link =  Link.new
  end

  def create
    @link = Link.new(link_params)
    @link.user_id = current_user.id
    if @link.save
      redirect_to link_url(@link)
    else
      flash.now[:errors] = @link.errors.full_messages
      render :new
    end
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    @link = current_user.links.find(params[:id])
    return nil unless @link
    if @link.update(link_params)
      redirect_to link_url(@link)
    else
      flash.now[:errors] = @link.errors.full_messages
      render :edit
    end

  end

  def show
  end

  def destroy
  end

  def index
    @links = Link.all
  end

  def link_params
    params.require(:link).permit(:title, :url)

  end
end

reddit_clone/reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if @user
      login!(@user)
      # redirect_to
    else
      flash.now[:errors] = ["Failed Credentials"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

reddit_clone/reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      # redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

reddit_clone/reddit_clone/app/helpers/application_helper.rb
module ApplicationHelper
end

reddit_clone/reddit_clone/app/helpers/comment_helper.rb
module CommentHelper
end

reddit_clone/reddit_clone/app/helpers/links_helper.rb
module LinksHelper
end

reddit_clone/reddit_clone/app/helpers/sessions_helper.rb
module SessionsHelper
end

reddit_clone/reddit_clone/app/helpers/users_helper.rb
module UsersHelper
end

reddit_clone/reddit_clone/app/views/comment/edit.html.erb
<h1>Comment#edit</h1>
<p>Find me in app/views/comment/edit.html.erb</p>

reddit_clone/reddit_clone/app/views/comment/new.html.erb
<h1>Comment#new</h1>
<p>Find me in app/views/comment/new.html.erb</p>

reddit_clone/reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
    <%= current_user.username %>
    <form class="" action="<%= session_url %>" method="post">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <input type="hidden" name="_method" value="delete">
      <input type="submit" name="" value="Sign Out!">

    </form>

    <% else %>
      <a href="<%= new_user_url %>">Sign Up</a>
      <a href="<%= new_session_url %>">Log In</a>
    <% end %>

    <% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
      <%= error %> <br>
      <% end %>
    <% end %>

    <%= yield %>
  </body>
</html>

reddit_clone/reddit_clone/app/views/links/edit.html.erb
<h1>Links#edit</h1>
<p>Find me in app/views/links/edit.html.erb</p>

reddit_clone/reddit_clone/app/views/links/index.html.erb
<h1>Links Index</h1>

  <a href="<%= new_link_url %>">New Link!!!</a>

<% @links.each do |link| %>
<%= link.title %> <br>
<%= link.url %> <br>
<%= link.user.username %> <br>


<% end %>

reddit_clone/reddit_clone/app/views/links/new.html.erb
<h1>New Link</h1>
<p>Find me in app/views/links/new.html.erb</p>

<form class="" action="<%= links_url  %>" method="post">
  <input type="hidden" name="authenticitiy_token" value="<%= form_authenticity_token %>">

  <label> Title
    <input type="text" name="link[title]" value="">
  </label>
  <label> URL
      <input type="text" name="link[url]" value="">
    </label>
    <input type="submit" name="" value="make link, and congrats if you found this page!">


</form>

reddit_clone/reddit_clone/app/views/links/show.html.erb
<h1>Links#show</h1>
<p>Find me in app/views/links/show.html.erb</p>

reddit_clone/reddit_clone/app/views/links/update.html.erb
<h1>Links#update</h1>
<p>Find me in app/views/links/update.html.erb</p>

reddit_clone/reddit_clone/app/views/shared/_auth.html.erb
<input type="hidden" name="authencity_token" value="<%= form_authenticity_token %>">

reddit_clone/reddit_clone/app/views/users/new.html.erb
<h1>Sign Up Now!</h1>

<form class="" action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Username
    <input type="text" name="user[username]" value="">
  </label>

  <label>Password
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" name="" value="Sign Up">
</form>